<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class EmailTemplatesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $this->command->info('🌱 Seeding email_templates...');
        
        // Clear existing data
        DB::table('email_templates')->truncate();
        
        $data = [
            ['id' => '1', 'template_name' => 'Job Notification', 'subject' => 'New Job Notification', 'body' => '<strong style=\\\"text-align: left;\\\" class=\\\"text-blue-color\\\">\\n                               Hi {{candidate_name}},\\n                            </strong>\\n                            <br/><br>\\n                            Notification of all Job opportunities updated on {{date}} in <a target=\\\"_blank\\\" href=\\\"{{app_url}}\\\">{{from_name}}</a>\\n                            <br/><br>\\n                            {{jobs}}\\n                            <strong style=\\\"display: block; margin-top: 15px;\\\" class=\\\"text-blue-color\\\">Regards, <br/>\\n                                {{from_name}}\\n                            </strong>', 'variables' => '{{candidate_name}}, {{app_url}}, {{from_name}}', 'created_at' => '2024-04-09 23:48:50', 'updated_at' => '2024-04-09 23:48:50'],
            ['id' => '2', 'template_name' => 'Contact Us', 'subject' => 'Thanks For Contacting', 'body' => '<strong style=\\\"text-align: left;\\\" class=\\\"text-blue-color\\\">\\n                                Hello! {{name}},\\n                            </strong>\\n                            <br/><br>\\n                            Thanks for contacting us.\\n                            <br/><br>\\n                            Quaerat facere dicta<br/><br>\\n                            Apart from the email, you can also contact me on my cell : {{phone_no}}<br><br>\\n                            <strong style=\\\"display: block; margin-top: 15px;\\\" class=\\\"text-blue-color\\\">Regards, <br/>\\n                                {{from_name}}\\n                            </strong>', 'variables' => '{{name}}, {{phone_no}}, {{from_name}}', 'created_at' => '2024-04-09 23:48:50', 'updated_at' => '2024-04-09 23:48:50'],
            ['id' => '3', 'template_name' => 'News Letter', 'subject' => '', 'body' => '<strong style=\\\"text-align: left;\\\" class=\\\"text-blue-color\\\">\\n                                Hello Dear,\\n                            </strong>\\n                            <br/><br>\\n                            New Notice from {{from_name}}. <br/><br>\\n                            {{description}}<br><br>\\n                            <strong style=\\\"display: block; margin-top: 15px;\\\" class=\\\"text-blue-color\\\">Regards, <br/>\\n                                {{from_name}}\\n                            </strong>', 'variables' => '{{description}}, {{from_name}}', 'created_at' => '2024-04-09 23:48:50', 'updated_at' => '2024-04-09 23:48:50'],
            ['id' => '4', 'template_name' => 'Email Job To Friend', 'subject' => 'Email for Job Details', 'body' => '<strong style=\\\"text-align: left;\\\" class=\\\"text-blue-color\\\">\\n                                Hi {{friend_name}},\\n                            </strong>\\n                            <br/><br>\\n                            I have send you the below job link in which you can find the relevant details for the same.\\n                            <br/><br>\\n                                Link : <a href=\\\"{{job_url}}\\\" target=\\\"_blank\\\">{{job_url}}</a>\\n                            <br><br>\\n                            <strong style=\\\"display: block; margin-top: 15px;\\\" class=\\\"text-blue-color\\\">Regards, <br/>\\n                                {{from_name}}\\n                            </strong>', 'variables' => '{{friend_name}}, {{job_url}}, {{from_name}}', 'created_at' => '2024-04-09 23:48:50', 'updated_at' => '2024-04-09 23:48:50'],
            ['id' => '5', 'template_name' => 'Job Alert', 'subject' => 'New Job Alert', 'body' => '<strong style=\\\"text-align: left;\\\" class=\\\"text-blue-color\\\">\\n                               Hi {{job_name}},\\n                            </strong>\\n                            <br/><br>\\n                            <h2>Job Title: {{job_title}}</h2>\\n                            <br/><br>\\n                            New job posted with {{job_title}}, if you are interested then you can apply for this job.<br><br><br>\\n                            <a href=\\\"{{job_url}}\\\" target=\\\"_blank\\\" style=\\\"display: table; margin: 0 auto;\\\">View Job</a>\\n                            <br><br>\\n                            <strong style=\\\"display: block; margin-top: 15px;\\\" class=\\\"text-blue-color\\\">Thanks, <br/>\\n                                {{from_name}}\\n                            </strong>', 'variables' => '{{job_name}},{{job_url}}, {{job_title}}, {{from_name}}', 'created_at' => '2024-04-09 23:48:50', 'updated_at' => '2024-04-09 23:48:50'],
            ['id' => '6', 'template_name' => 'Candidate Job Applied', 'subject' => 'Job Applied by Candidate', 'body' => '<strong style=\\\"text-align: left;\\\" class=\\\"text-blue-color\\\">\\n                                Hi {{employer_fullName}},\\n                            </strong>\\n                            <br/><br>\\n                            <h2>Someone just applied for job : {{job_title}}</h2>\\n                            <br/><br>\\n                            My name is {{candidate_name}}<br><br>\\n                            I have go through with your job details and thereby i have applied for the same. Please kindly contact me if i found suitable based on your needs.<br><br><br>\\n                            <a href=\\\"{{candidate_details_url}}\\\" target=\\\"_blank\\\" style=\\\"display: table; margin: 0 auto;\\\">View Candidate Profile</a>\\n                            <br><br>\\n                            <strong style=\\\"display: block; margin-top: 15px;\\\" class=\\\"text-blue-color\\\">Regards, <br/>\\n                                {{from_name}}\\n                            </strong>', 'variables' => '{{employer_fullName}},{{candidate_name}},{{candidate_details_url}}, {{job_title}}, {{from_name}}', 'created_at' => '2024-04-09 23:48:50', 'updated_at' => '2024-04-09 23:48:50'],
            ['id' => '7', 'template_name' => 'Verify Email', 'subject' => 'Verify Email Address', 'body' => '<strong style=\\\"text-align: left;\\\" class=\\\"text-blue-color\\\">\\n                                Hello! {{user_name}},\\n                            </strong>\\n                            <br/><br>\\n                            Please click the button below to verify your email address.\\n                            <br/><br><br>\\n                                <a href=\\\"{{verify_url}}\\\" style=\\\"display: table; margin: 0 auto;\\\">Verify Email Address</a>\\n                            <br><br>\\n                            If you did not create an account, no further action is required.<br><br>\\n                            <strong style=\\\"display: block; margin-top: 15px;\\\" class=\\\"text-blue-color\\\">Regards, <br/>\\n                                {{from_name}}\\n                            </strong>', 'variables' => '{{user_name}},{{verify_url}},{{from_name}}', 'created_at' => '2024-04-09 23:48:50', 'updated_at' => '2024-04-09 23:48:50'],
            ['id' => '8', 'template_name' => 'Password Reset Email', 'subject' => 'Reset Password Notification', 'body' => '<strong style=\\\"text-align: left; font-family: Circular Std, sans-serif !important;\\\" class=\\\"text-blue-color\\\">\\n                                Hello!,\\n                            </strong>\\n                            <br>\\n                            <p style=\\\"font-family: Circular Std, sans-serif !important;\\\">You are receiving this email because we received a password reset request for your account.</p>\\n                            <br>\\n                            <a href=\\\"{{reset_url}}\\\" style=\\\"display: table; margin: 0 auto; font-family: Circular Std, sans-serif !important;\\\">Reset Password</a>\\n                            <br>\\n                            <p style=\\\"font-family: Circular Std, sans-serif !important;\\\">This password reset link will expire in 60 minutes.</p><br>\\n                            <p style=\\\"font-family: Circular Std, sans-serif !important;\\\">If you did not request a password reset, no further action is required.</p><br>\\n                            <strong style=\\\"display: block; margin-top: 15px; font-family: Circular Std, sans-serif !important;\\\" class=\\\"text-blue-color\\\">Regards,<br>\\n                                {{from_name}}\\n                            </strong>\\n', 'variables' => '{{reset_url}},{{from_name}}', 'created_at' => '2024-04-09 23:48:50', 'updated_at' => '2024-04-09 23:48:51'],
        ];
        
        if (empty($data)) {
            $this->command->info('⚠️  No data to seed for email_templates');
            return;
        }
        
        // Insert data
        DB::table('email_templates')->insert($data);
        
        $this->command->info('✅ Seeded ' . count($data) . ' email_templates records');
    }
}