#!/bin/bash

echo "=== CREATING ALL MISSING REQUEST FILES ==="
echo "Total files to create: 162"
echo ""

# Array of all missing request files
declare -a requests=(
    "EditProfileCandidateRequest"
    "UpdateProfileCandidateRequest"
    "UpdateGeneralInformationCandidateRequest"
    "UpdateOnlineProfileCandidateRequest"
    "UploadResumeCandidateRequest"
    "UpdateJobAlertCandidateRequest"
    "ChangePasswordCandidateRequest"
    "ProfileUpdateCandidateRequest"
    "ChoosePreferenceCandidateRequest"
    "CreateExperienceCandidateProfileRequest"
    "UpdateExperienceCandidateProfileRequest"
    "CreateEducationCandidateProfileRequest"
    "UpdateEducationCandidateProfileRequest"
    "CreateMaritalStatusRequest"
    "UpdateMaritalStatusRequest"
    "ChangePasswordUserRequest"
    "ProfileUpdateUserRequest"
    "UpdateLanguageUserRequest"
    "AdminCreateUserRequest"
    "AdminStoreUserRequest"
    "AdminUpdateUserRequest"
    "CreateSessionFeaturedCompanySubscriptionRequest"
    "PaymentSuccessFeaturedCompanySubscriptionRequest"
    "CreateTranslationManagerRequest"
    "UpdateTranslationManagerRequest"
    "UpdateNotificationSettingsRequest"
    "CreateJobCategoryRequest"
    "UpdateJobCategoryRequest"
    "CreateTestimonialsRequest"
    "UpdateTestimonialsRequest"
    "CreateCompanyRequest"
    "UpdateCompanyRequest"
    "GetStatesCompanyRequest"
    "GetCitiesCompanyRequest"
    "UpdateCompanyCompanyRequest"
    "ShowReportedCompanyNoteCompanyRequest"
    "CreateStateRequest"
    "UpdateStateRequest"
    "RedirectToVerificationRequest"
    "VerifyVerificationRequest"
    "DashboardChartDataDashboardRequest"
    "EmployerDashboardChartDashboardRequest"
    "SendContactEmailHomeRequest"
    "ChangeLanguageHomeRequest"
    "GetJobsSearchHomeRequest"
    "GetCompaniesListsCompanyRequest"
    "SaveFavouriteCompanyCompanyRequest"
    "ReportToCompanyCompanyRequest"
    "CreateCandidateRequest"
    "UpdateCandidateRequest"
    "GetCandidatesListsCandidateRequest"
    "BlogCommentStorePostRequest"
    "BlogCommentUpdatePostRequest"
    "CreateJobRequest"
    "UpdateJobRequest"
    "SaveFavouriteJobJobRequest"
    "ReportJobAbuseJobRequest"
    "EmailJobToFriendJobRequest"
    "RegisterRegisterRequest"
    "ApplyJobJobApplicationRequest"
    "NewsLetterWebRequest"
    "CreateTransactionRequest"
    "UpdateTransactionRequest"
    "CreateJobNotificationRequest"
    "ChangePasswordEmployerRequest"
    "ProfileUpdateEmployerRequest"
    "UpdateFrontSettingsRequest"
    "UpdateEmailTemplateRequest"
    "CreateSalaryPeriodRequest"
    "UpdateSalaryPeriodRequest"
    "ReportCandidateCandidateRequest"
    "ShowReportedCandiateNoteCandidateRequest"
    "UpdateSettingRequest"
    "CreateJobStageRequest"
    "UpdateJobStageRequest"
    "GetPaymentStatusPaypalRequest"
    "CreateOwnerShipTypeRequest"
    "UpdateOwnerShipTypeRequest"
    "CreatePostRequest"
    "UpdatePostRequest"
    "CreateImageSliderRequest"
    "UpdateImageSliderRequest"
    "PurchaseSubscriptionSubscriptionRequest"
    "PaymentSuccessSubscriptionRequest"
    "CancelSubscriptionSubscriptionRequest"
    "UpdateSubscriptionSubscriptionRequest"
    "ChangeTransactionStatusSubscriptionRequest"
    "CreatePostCategoryRequest"
    "UpdatePostCategoryRequest"
    "CreateBrandingSliderRequest"
    "UpdateBrandingSliderRequest"
    "AboutUsServiceCmsServicesRequest"
    "UpdateCmsServicesRequest"
    "AboutUsUpdateCmsServicesRequest"
    "CreatePlanRequest"
    "UpdatePlanRequest"
    "GetStatesJobRequest"
    "GetCitiesJobRequest"
    "StoreJobJobRequest"
    "UpdateJobJobRequest"
    "CreateRequiredDegreeLevelRequest"
    "UpdateRequiredDegreeLevelRequest"
    "UpdatePrivacyPolicyRequest"
    "CreateCityRequest"
    "UpdateCityRequest"
    "CreateCareerLevelRequest"
    "UpdateCareerLevelRequest"
    "CreateJobShiftRequest"
    "UpdateJobShiftRequest"
    "CreateTagRequest"
    "UpdateTagRequest"
    "CreateNoticeboardRequest"
    "UpdateNoticeboardRequest"
    "CreateLanguageRequest"
    "UpdateLanguageRequest"
    "ChangeLanguageLanguageRequest"
    "DeleteJobApplicationRequest"
    "ChangeJobApplicationStatusJobApplicationRequest"
    "DownloadMediaJobApplicationRequest"
    "GetJobStageJobApplicationRequest"
    "ChangeJobStageJobApplicationRequest"
    "ViewSlotsScreenJobApplicationRequest"
    "InterviewSlotStoreJobApplicationRequest"
    "BatchSlotStoreJobApplicationRequest"
    "EditSlotJobApplicationRequest"
    "UpdateSlotJobApplicationRequest"
    "SlotDestroyJobApplicationRequest"
    "GetScheduleHistoryJobApplicationRequest"
    "CancelSelectedSlotJobApplicationRequest"
    "CreateFunctionalAreaRequest"
    "UpdateFunctionalAreaRequest"
    "CreateSalaryCurrencyRequest"
    "UpdateSalaryCurrencyRequest"
    "CreateHeaderSliderRequest"
    "UpdateHeaderSliderRequest"
    "CreateFAQRequest"
    "UpdateFAQRequest"
    "CreateSessionFeaturedJobSubscriptionRequest"
    "PaymentSuccessFeaturedJobSubscriptionRequest"
    "CreateJobTypeRequest"
    "UpdateJobTypeRequest"
    "CreateCountryRequest"
    "UpdateCountryRequest"
    "CreateSkillRequest"
    "UpdateSkillRequest"
    "CreateIndustryRequest"
    "UpdateIndustryRequest"
    "CreateCompanySizeRequest"
    "UpdateCompanySizeRequest"
    "CreateAdminRequest"
    "UpdateAdminRequest"
    "GetStatesLocationRequest"
    "GetCitiesLocationRequest"
    "GetDashboardDataRealTimeRequest"
    "UpdateApplicationStatusRealTimeRequest"
    "GetWebSocketAuthRealTimeRequest"
    "GetActivityFeedRealTimeRequest"
    "CreateBlogCommentRequest"
)

# Counter for progress tracking
counter=1
total=${#requests[@]}

# Create each request file
for request in "${requests[@]}"; do
    echo "[$counter/$total] Creating $request..."
    php artisan make:request "$request"
    counter=$((counter + 1))
done

echo ""
echo "=== COMPLETED ==="
echo "Created $total request files successfully!"
echo "Next step: Add validation rules to each request file" 